[platformio]
default_envs = esp32dev
src_dir = Bambu-Poop-Conveyor

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
lib_deps =
  bblanchon/ArduinoJson@6.21.5
  knolleary/PubSubClient@2.8
  https://github.com/jnthas/Improv-WiFi-Library.git#e37c244e0080349e191252acf4bce146eca118e0
build_flags =
  -DCORE_DEBUG_LEVEL=0
