#!/usr/bin/env python3
"""Compress the self-contained ESP32 UI into a PROGMEM header."""
from gzip import compress
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
source = (ROOT / "web" / "index.html").read_bytes()
payload = compress(source, compresslevel=9, mtime=0)
rows = []
for offset in range(0, len(payload), 16):
    rows.append("  " + ", ".join(f"0x{byte:02x}" for byte in payload[offset:offset + 16]) + ",")
header = """// Generated by scripts/generate_ui.py. Do not edit by hand.\n#pragma once\n#include <Arduino.h>\n\nstatic const uint8_t WEB_UI_GZIP[] PROGMEM = {\n%s\n};\nstatic const size_t WEB_UI_GZIP_LEN = sizeof(WEB_UI_GZIP);\n""" % "\n".join(rows)
(ROOT / "Bambu-Poop-Conveyor" / "generated_ui.h").write_text(header)
print(f"UI: {len(source)} bytes -> {len(payload)} bytes gzip")
